//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""PlayerControls"",
            ""id"": ""e5b18e61-d01e-41cc-8b6e-c495b064f506"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9cf6a36a-7a71-4b78-b369-3d119e657c12"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StoneTrowing"",
                    ""type"": ""Value"",
                    ""id"": ""0ae94f44-98a5-4ce1-a1eb-9c6f84f45974"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ActivateThrowMode"",
                    ""type"": ""Button"",
                    ""id"": ""511975c4-cb35-434a-be95-0f9c49ef63c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASDKeys"",
                    ""id"": ""2c5f9b81-70ea-4d23-a39f-2bc9e5997f38"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""592677dc-4ca0-4e5e-bfb3-237c69ab0064"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""3a975b92-aa60-4672-bbd9-e8c9d8906034"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""a71a2efe-4a20-4f3c-9f1d-58d8cc278be4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8946127e-6aea-4c42-9d55-f727e12675cf"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""077f520c-f2f9-4323-9401-5c5d49cca4bd"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""DPad"",
                    ""id"": ""e22da76b-04f9-450b-97f9-5c98929107d2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bd89fc5f-d242-4beb-a5cc-b06d46093334"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""94d5b1e5-20f9-4e5f-9406-33f87c62c7f7"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ad71ceee-80c5-4e1f-8c71-5be43b4d10de"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""StoneTrowing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""ba8707a1-0d80-449e-b3c6-97d0dbefd006"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StoneTrowing"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""8645dd84-905e-441c-96d3-7b0178df2a14"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""StoneTrowing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""4ddcb93f-bb88-49d3-9d9c-d1bae69cbcf7"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""StoneTrowing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""7acc0721-a680-42b6-9a1d-ba0191dc3a0e"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StoneTrowing"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""cc09a2b8-79b9-4d95-b318-6010153e784f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Gamepad"",
                    ""action"": ""StoneTrowing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""fb8653a5-3943-40fa-a250-9901fe7d8b2d"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Gamepad"",
                    ""action"": ""StoneTrowing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9b61c6c7-258d-4e80-a0fd-cf228204f15a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Gamepad"",
                    ""action"": ""ActivateThrowMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Level 07"",
            ""id"": ""66cf8bc6-7a09-4af7-8d8e-687936976d85"",
            ""actions"": [
                {
                    ""name"": ""Strike"",
                    ""type"": ""Button"",
                    ""id"": ""b47e6349-1fe2-4118-a75a-6d48bd0202bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Walk"",
                    ""type"": ""Value"",
                    ""id"": ""4172b513-7c85-441e-a264-a7523f588054"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""4d635347-1904-4fbc-b8e3-6391f7cc48e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f4c5bcdc-9b93-47bd-938b-87ffac3afaf8"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strike"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5e8ba03-5e5e-4437-81d4-4ab25e1a15c5"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strike"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""5edbde26-cc31-4657-8c47-fd80d6dbf4dc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d7a5bd2c-e6c3-4462-875c-ba6a029be4e5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1e07aaa3-fac5-4d3b-ba7a-87e97a977ffd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""7f5e06ad-44fc-4403-b054-7953bf16fdbd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""368bcffe-6c53-46a8-91d2-44a0fa322650"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c204cb36-ef64-413f-9655-7772bd5076c3"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""58fb5c62-f6f2-45be-860e-0506996541b5"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9176bbf6-9974-429b-8929-6d61d68386eb"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Level 09"",
            ""id"": ""5a41e674-df8c-4bba-977a-c5ce0e56eb2c"",
            ""actions"": [
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""a62d684a-105e-46cd-bfb6-9ffef322c5d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Value"",
                    ""id"": ""e489458b-929f-4f5a-a9db-b93516af5683"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9268bd0a-9009-4d50-af14-78bbd917df3c"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6800907e-6064-4cbb-9909-7187abe24cf7"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Story"",
            ""id"": ""bb5bc2af-5e74-4f4f-a978-24199ed0d4ce"",
            ""actions"": [
                {
                    ""name"": ""Next"",
                    ""type"": ""Button"",
                    ""id"": ""65c64d39-5bf0-40af-881e-82ec6e79ad4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Previous"",
                    ""type"": ""Button"",
                    ""id"": ""c66b24b9-cc00-440e-8d13-039f6e04f1a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""58becf82-21e4-4fe4-82c2-e25cab52e8ea"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56c9de12-26aa-47e6-9039-6c4d6e55e1f6"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Previous"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Xbox Gamepad"",
            ""bindingGroup"": ""Xbox Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerControls
        m_PlayerControls = asset.FindActionMap("PlayerControls", throwIfNotFound: true);
        m_PlayerControls_Movement = m_PlayerControls.FindAction("Movement", throwIfNotFound: true);
        m_PlayerControls_StoneTrowing = m_PlayerControls.FindAction("StoneTrowing", throwIfNotFound: true);
        m_PlayerControls_ActivateThrowMode = m_PlayerControls.FindAction("ActivateThrowMode", throwIfNotFound: true);
        // Level 07
        m_Level07 = asset.FindActionMap("Level 07", throwIfNotFound: true);
        m_Level07_Strike = m_Level07.FindAction("Strike", throwIfNotFound: true);
        m_Level07_Walk = m_Level07.FindAction("Walk", throwIfNotFound: true);
        m_Level07_Block = m_Level07.FindAction("Block", throwIfNotFound: true);
        // Level 09
        m_Level09 = asset.FindActionMap("Level 09", throwIfNotFound: true);
        m_Level09_Shoot = m_Level09.FindAction("Shoot", throwIfNotFound: true);
        m_Level09_Aim = m_Level09.FindAction("Aim", throwIfNotFound: true);
        // Story
        m_Story = asset.FindActionMap("Story", throwIfNotFound: true);
        m_Story_Next = m_Story.FindAction("Next", throwIfNotFound: true);
        m_Story_Previous = m_Story.FindAction("Previous", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControls
    private readonly InputActionMap m_PlayerControls;
    private IPlayerControlsActions m_PlayerControlsActionsCallbackInterface;
    private readonly InputAction m_PlayerControls_Movement;
    private readonly InputAction m_PlayerControls_StoneTrowing;
    private readonly InputAction m_PlayerControls_ActivateThrowMode;
    public struct PlayerControlsActions
    {
        private @Controls m_Wrapper;
        public PlayerControlsActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerControls_Movement;
        public InputAction @StoneTrowing => m_Wrapper.m_PlayerControls_StoneTrowing;
        public InputAction @ActivateThrowMode => m_Wrapper.m_PlayerControls_ActivateThrowMode;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControlsActions instance)
        {
            if (m_Wrapper.m_PlayerControlsActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovement;
                @StoneTrowing.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnStoneTrowing;
                @StoneTrowing.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnStoneTrowing;
                @StoneTrowing.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnStoneTrowing;
                @ActivateThrowMode.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnActivateThrowMode;
                @ActivateThrowMode.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnActivateThrowMode;
                @ActivateThrowMode.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnActivateThrowMode;
            }
            m_Wrapper.m_PlayerControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @StoneTrowing.started += instance.OnStoneTrowing;
                @StoneTrowing.performed += instance.OnStoneTrowing;
                @StoneTrowing.canceled += instance.OnStoneTrowing;
                @ActivateThrowMode.started += instance.OnActivateThrowMode;
                @ActivateThrowMode.performed += instance.OnActivateThrowMode;
                @ActivateThrowMode.canceled += instance.OnActivateThrowMode;
            }
        }
    }
    public PlayerControlsActions @PlayerControls => new PlayerControlsActions(this);

    // Level 07
    private readonly InputActionMap m_Level07;
    private ILevel07Actions m_Level07ActionsCallbackInterface;
    private readonly InputAction m_Level07_Strike;
    private readonly InputAction m_Level07_Walk;
    private readonly InputAction m_Level07_Block;
    public struct Level07Actions
    {
        private @Controls m_Wrapper;
        public Level07Actions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Strike => m_Wrapper.m_Level07_Strike;
        public InputAction @Walk => m_Wrapper.m_Level07_Walk;
        public InputAction @Block => m_Wrapper.m_Level07_Block;
        public InputActionMap Get() { return m_Wrapper.m_Level07; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Level07Actions set) { return set.Get(); }
        public void SetCallbacks(ILevel07Actions instance)
        {
            if (m_Wrapper.m_Level07ActionsCallbackInterface != null)
            {
                @Strike.started -= m_Wrapper.m_Level07ActionsCallbackInterface.OnStrike;
                @Strike.performed -= m_Wrapper.m_Level07ActionsCallbackInterface.OnStrike;
                @Strike.canceled -= m_Wrapper.m_Level07ActionsCallbackInterface.OnStrike;
                @Walk.started -= m_Wrapper.m_Level07ActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_Level07ActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_Level07ActionsCallbackInterface.OnWalk;
                @Block.started -= m_Wrapper.m_Level07ActionsCallbackInterface.OnBlock;
                @Block.performed -= m_Wrapper.m_Level07ActionsCallbackInterface.OnBlock;
                @Block.canceled -= m_Wrapper.m_Level07ActionsCallbackInterface.OnBlock;
            }
            m_Wrapper.m_Level07ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Strike.started += instance.OnStrike;
                @Strike.performed += instance.OnStrike;
                @Strike.canceled += instance.OnStrike;
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
                @Block.started += instance.OnBlock;
                @Block.performed += instance.OnBlock;
                @Block.canceled += instance.OnBlock;
            }
        }
    }
    public Level07Actions @Level07 => new Level07Actions(this);

    // Level 09
    private readonly InputActionMap m_Level09;
    private ILevel09Actions m_Level09ActionsCallbackInterface;
    private readonly InputAction m_Level09_Shoot;
    private readonly InputAction m_Level09_Aim;
    public struct Level09Actions
    {
        private @Controls m_Wrapper;
        public Level09Actions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Shoot => m_Wrapper.m_Level09_Shoot;
        public InputAction @Aim => m_Wrapper.m_Level09_Aim;
        public InputActionMap Get() { return m_Wrapper.m_Level09; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Level09Actions set) { return set.Get(); }
        public void SetCallbacks(ILevel09Actions instance)
        {
            if (m_Wrapper.m_Level09ActionsCallbackInterface != null)
            {
                @Shoot.started -= m_Wrapper.m_Level09ActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_Level09ActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_Level09ActionsCallbackInterface.OnShoot;
                @Aim.started -= m_Wrapper.m_Level09ActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m_Level09ActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m_Level09ActionsCallbackInterface.OnAim;
            }
            m_Wrapper.m_Level09ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
            }
        }
    }
    public Level09Actions @Level09 => new Level09Actions(this);

    // Story
    private readonly InputActionMap m_Story;
    private IStoryActions m_StoryActionsCallbackInterface;
    private readonly InputAction m_Story_Next;
    private readonly InputAction m_Story_Previous;
    public struct StoryActions
    {
        private @Controls m_Wrapper;
        public StoryActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Next => m_Wrapper.m_Story_Next;
        public InputAction @Previous => m_Wrapper.m_Story_Previous;
        public InputActionMap Get() { return m_Wrapper.m_Story; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StoryActions set) { return set.Get(); }
        public void SetCallbacks(IStoryActions instance)
        {
            if (m_Wrapper.m_StoryActionsCallbackInterface != null)
            {
                @Next.started -= m_Wrapper.m_StoryActionsCallbackInterface.OnNext;
                @Next.performed -= m_Wrapper.m_StoryActionsCallbackInterface.OnNext;
                @Next.canceled -= m_Wrapper.m_StoryActionsCallbackInterface.OnNext;
                @Previous.started -= m_Wrapper.m_StoryActionsCallbackInterface.OnPrevious;
                @Previous.performed -= m_Wrapper.m_StoryActionsCallbackInterface.OnPrevious;
                @Previous.canceled -= m_Wrapper.m_StoryActionsCallbackInterface.OnPrevious;
            }
            m_Wrapper.m_StoryActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Next.started += instance.OnNext;
                @Next.performed += instance.OnNext;
                @Next.canceled += instance.OnNext;
                @Previous.started += instance.OnPrevious;
                @Previous.performed += instance.OnPrevious;
                @Previous.canceled += instance.OnPrevious;
            }
        }
    }
    public StoryActions @Story => new StoryActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_XboxGamepadSchemeIndex = -1;
    public InputControlScheme XboxGamepadScheme
    {
        get
        {
            if (m_XboxGamepadSchemeIndex == -1) m_XboxGamepadSchemeIndex = asset.FindControlSchemeIndex("Xbox Gamepad");
            return asset.controlSchemes[m_XboxGamepadSchemeIndex];
        }
    }
    public interface IPlayerControlsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnStoneTrowing(InputAction.CallbackContext context);
        void OnActivateThrowMode(InputAction.CallbackContext context);
    }
    public interface ILevel07Actions
    {
        void OnStrike(InputAction.CallbackContext context);
        void OnWalk(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
    }
    public interface ILevel09Actions
    {
        void OnShoot(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
    }
    public interface IStoryActions
    {
        void OnNext(InputAction.CallbackContext context);
        void OnPrevious(InputAction.CallbackContext context);
    }
}
